// supabase/functions/auth-verify-qr/index.ts
// New device scans QR generated by old device → verify HMAC signature,
// bump session_version, issue new JWT, old device gets invalidated on next sync

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.0';
import { signJWT } from '../_shared/jwt.ts';
import { corsHeaders, handleCors } from '../_shared/cors.ts';

const supabase = createClient(
  Deno.env.get('SUPABASE_URL')!,
  Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
);

async function hmacSign(data: string, secret: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(data));
  return Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

Deno.serve(async (req: Request) => {
  const corsResponse = handleCors(req);
  if (corsResponse) return corsResponse;

  try {
    const { qr_data, new_device_id } = await req.json();

    const decoded = new TextDecoder().decode(
      Uint8Array.from(atob(qr_data), (c) => c.charCodeAt(0))
    );
    const parts = decoded.split(':');

    if (parts.length !== 4) {
      return jsonResponse({ error: 'Invalid QR format' }, 400);
    }

    const [oldDeviceId, sessionVersionStr, timestampStr, signature] = parts;

    // Timestamp check — 2 min max validity
    const qrTimestamp = parseInt(timestampStr);
    if (Date.now() - qrTimestamp > 120_000) {
      return jsonResponse({ error: 'QR code expired' }, 401);
    }

    // Verify HMAC — secret derived from old device ID + shared app secret
    const payload = `${oldDeviceId}:${sessionVersionStr}:${timestampStr}`;
    const expectedSig = await hmacSign(payload, `${oldDeviceId}:tata`);

    if (signature !== expectedSig) {
      return jsonResponse({ error: 'Invalid QR signature' }, 401);
    }

    // Find user by old device ID
    const { data: user, error: findErr } = await supabase
      .from('users')
      .select('id, phone, session_version')
      .eq('device_id', oldDeviceId)
      .maybeSingle();

    if (findErr || !user) {
      return jsonResponse({ error: 'User not found' }, 401);
    }

    const newSessionVersion = user.session_version + 1;

    const { error: updateErr } = await supabase
      .from('users')
      .update({
        session_version: newSessionVersion,
        device_id: new_device_id,
        updated_at: new Date().toISOString(),
      })
      .eq('id', user.id);

    if (updateErr) throw updateErr;

    const newJWT = await signJWT({
      userId: user.id,
      phone: user.phone,
      sessionVersion: newSessionVersion,
      deviceId: new_device_id,
    });

    await supabase.from('audit_log').insert({
      user_id: user.id,
      event: 'new_device_login',
      details: { oldDeviceId, newDeviceId: new_device_id, sessionVersion: newSessionVersion },
    });

    return jsonResponse({
      success: true,
      jwt: newJWT,
      session_version: newSessionVersion,
    });
  } catch (err) {
    console.error('QR verification error:', err);
    return jsonResponse({ error: 'QR verification failed' }, 500);
  }
});

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}
