// supabase/functions/auth-whatsapp-webhook/index.ts
// Toggleable via ENABLE_WHATSAPP env flag — Meta Cloud API webhook format

import { upstash } from '../_shared/upstash.ts';
import { corsHeaders, handleCors } from '../_shared/cors.ts';

Deno.serve(async (req: Request) => {
  const corsResponse = handleCors(req);
  if (corsResponse) return corsResponse;

  // Hard kill switch — flip ENABLE_WHATSAPP=false in Supabase secrets to disable
  // instantly without touching this code or the verification waterfall logic.
  if (Deno.env.get('ENABLE_WHATSAPP') !== 'true') {
    return jsonResponse({ status: 'whatsapp_disabled' }, 200);
  }

  try {
    const body = await req.json();

    // Meta Cloud API webhook structure (different from old Twilio-style 'From'/'Body')
    const entry = body.entry?.[0];
    const change = entry?.changes?.[0];
    const message = change?.value?.messages?.[0];

    if (!message) {
      return jsonResponse({ status: 'no_message' }, 200);
    }

    const from = message.from; // e.g. "919876543210"
    const text = message.text?.body ?? '';
    const phone = from.replace(/\D/g, '').slice(-10);

    const match = text.match(/REG-([A-Z0-9]{8})/);
    if (!match) {
      return jsonResponse({ status: 'ignored' }, 200);
    }

    const incomingToken = match[1];

    // The token was originally generated by your app and shown to the user
    // to send back — verify it matches what you issued
    const redisKey = `pending_whatsapp:${phone}`;
    const issuedToken = await upstash.get(redisKey);

    if (issuedToken !== incomingToken) {
      return jsonResponse({ status: 'token_mismatch' }, 200);
    }

    // Promote to verified token for the register endpoint to consume
    const verifiedToken = crypto.randomUUID().replace(/-/g, '').slice(0, 16);
    await upstash.setex(`verify:whatsapp:${phone}`, 5 * 60, verifiedToken);
    await upstash.del(redisKey);

    return jsonResponse({ success: true, phone, token: verifiedToken });
  } catch (err) {
    console.error('WhatsApp webhook error:', err);
    return jsonResponse({ error: 'Webhook processing failed' }, 500);
  }
});

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

/*
SETUP NOTE (Meta Cloud API, no third-party BSP):

1. Create a Meta Developer App → add WhatsApp product
2. Get a test number (free) or register your own business number
3. Set webhook URL to: https://<project>.supabase.co/functions/v1/auth-whatsapp-webhook
4. Subscribe to 'messages' field
5. Meta gives ~1000 free service conversations/month per number on Cloud API direct,
   then bills per-conversation (~₹0.40-0.80 depending on category/region) — NOT a flat
   monthly fee like third-party BSPs (Gupshup/Twilio) charge. Budget accordingly.
6. Set ENABLE_WHATSAPP=true in Supabase secrets once template messages are approved
   (Meta requires template approval before you can send the "send REG-XXXX" prompt
   as an outbound message — incoming messages from users don't need template approval).
*/
